# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Nil Venet
tagline:          'Statistics at Bergamo University'
description:      'Researcher in Statistics at Bergamo University'
url:              https://nilvenet.github.io
baseurl:          ""

author:
  name:           'Nil Venet'
  url:            "https://nilvenet.github.io"

#paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/nilvenet.github.io

#gems:
#  - jekyll-last-modified-at

#coauthors url
bachoc:	   	https://www.math.univ-toulouse.fr/~fbachoc/
loubes:		https://perso.math.univ-toulouse.fr/loubes/
gamboa:		https://www.math.univ-toulouse.fr/~gamboa/
fasso:		https://www.unibg.it/pers/?alessandro.fasso	
finazzi:	https://www.unibg.it/pers/?francesco.finazzi
